const S = {
  page: { minHeight: '100vh', background: '#f5f6f7', color: '#111827', fontFamily: "'Noto Sans TC', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" },
  shell: { display: 'flex', minHeight: '100vh' },
  sidebar: { width: 250, background: '#ffffff', color: '#6b7280', padding: '16px 0 12px', borderRight: '1px solid #e5e7eb', position: 'sticky', top: 0, height: '100vh', overflowY: 'auto' },
  main: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', background: '#f5f6f7' },
  header: { minHeight: 52, background: '#ffffff', borderBottom: '1px solid #e5e7eb', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 28px', position: 'sticky', top: 0, zIndex: 100 },
  content: { flex: 1, padding: '20px 28px 32px', minHeight: 'calc(100vh - 52px)' },
  card: { background: '#ffffff', border: '1px solid #e5e7eb', borderRadius: 12, padding: '16px 18px', marginBottom: 12, boxShadow: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)', transition: 'all 0.25s ease' },
  panelMuted: { background: '#eeeeee', border: '1px solid #e5e7eb', borderRadius: 10, padding: '10px 14px' },
  input: { background: '#ffffff', border: '1px solid #e5e7eb', borderRadius: 8, padding: '7px 12px', color: '#111827', fontSize: 13, outline: 'none', width: '100%', boxSizing: 'border-box', fontFamily: "'Noto Sans TC', sans-serif", transition: 'border-color 0.2s, box-shadow 0.2s' },
  btnPrimary: { background: '#16a34a', color: '#fff', border: 'none', borderRadius: 8, padding: '7px 16px', fontWeight: 600, cursor: 'pointer', fontSize: 13, fontFamily: "'Noto Sans TC', sans-serif", letterSpacing: 0.2, boxShadow: '0 1px 2px rgba(0,0,0,0.05)', transition: 'background 0.15s, box-shadow 0.15s' },
  btnGhost: { background: '#fff', color: '#374151', border: '1px solid #e5e7eb', borderRadius: 8, padding: '6px 14px', cursor: 'pointer', fontSize: 13, fontFamily: "'Noto Sans TC', sans-serif", transition: 'border-color 0.15s, background 0.15s' },
  btnLine: { background: '#06c755', color: '#fff', border: 'none', borderRadius: 8, padding: '7px 16px', fontWeight: 600, cursor: 'pointer', fontSize: 13, boxShadow: '0 1px 3px rgba(6,199,85,0.3)' },
  label: { color: '#6b7280', fontSize: 11, fontWeight: 600, display: 'block', marginBottom: 4, letterSpacing: 0.5 },
  mono: { fontFamily: "'SF Mono', 'Fira Code', 'Cascadia Code', monospace", letterSpacing: 0.3 },
  pageLead: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 14, marginBottom: 16 },
  pageTitle: { fontSize: 20, fontWeight: 700, color: '#111827', letterSpacing: -0.3, marginBottom: 2 },
  pageDesc: { fontSize: 13, color: '#6b7280', lineHeight: 1.6, maxWidth: 760 },
  eyebrow: { fontSize: 11, color: '#16a34a', fontWeight: 600, letterSpacing: 1.2, textTransform: 'uppercase', marginBottom: 4, ...{ fontFamily: "'SF Mono', 'Fira Code', monospace" } },
  statGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12, marginBottom: 16 },
  twoCol: { display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 12, alignItems: 'start' },
  tag: (color) => ({ display: 'inline-block', fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 4, background: color === 'green' ? '#dcfce7' : color === 'red' ? '#fee2e2' : color === 'line' ? '#dcfce7' : '#f3f4f6', color: color === 'green' ? '#16a34a' : color === 'red' ? '#ef4444' : color === 'line' ? '#16a34a' : '#374151', border: 'none' }),
};

export default S;
